### PR TITLE
Feature/23 refactor exceptions

### PR DESCRIPTION
**Pull request by michalrys**
It resolves: https://github.com/EngineCodeDev/ec-commons/issues/23

Changes:
- change exceptions type to check one
- out exceptions extend EngineCodeException
- ExceptionHandler was simplified
- errorDetails was removed - it is never used
- update ResponseEntity body - there must be always code (at least default one) and message
- Exception can return: message, http error code, our EngineCodeError id - customizable
- change ErrorCode and its enum -> in enum we could create our own error codes, customized - they shall be printed to user.
- these changes required changes in weeds-plantcare-service → see pull request:  https://github.com/EngineCodeDev/weeds-plantcare-service/pull/53

### CODE REVIEW

**Review by tom-zoladz — COMMENTED** [review]
I am against using checked exceptions. They can be useful in some cases when exposing the library to other APIs, but I did a small research and my conclusion is as following:
- exceptions inheriting from the same class `EngineCodeException` are unnecessarily checked as they are caught in the same handler anyway - `@ExceptionHandler(EngineCodeException.class)` (regardless of whether all methods have `throws …` clause or not)
- checked exceptions violate OCP
- checked exceptions are useful when you expose the library to other API and want to force the user to handle the specific exception that your library throws, but we throw our custom exceptions in our app and we catch them in the same app
- one of well known good practices is to **throw early, catch late** which makes us inform each intermediate method (when using checked excpts) that the exception can be thrown, which is less convenient and less readable than simply let the exception propagate to where it is caught/handled
- small change regarding exception at a low level can cause large refactoring of the intermediate methods that propagate the exception to higher levels, but when using runtime exception no refactoring is needed

So the checked exceptions are necessary sometimes, but it cannot be rule of thumb that we remove all runtime excpts and replace them with the checked ones.

Therefore we should stay with the runtime exceptions that were there from the beginning and just simplify the way they are used, we can talk about that.

**Comment by michalrys** [comment]
I suggest to discuss it internally - my remarks to discuss internally,

> I am against using checked exceptions. They can be useful in some cases when exposing the library to other APIs, but I did a small research and my conclusion is as following:

We expose ec-common (library) to other apps (other APIs) so this is such case? But OK, the only gain of using checked exceptions in our case is that we have to use 'throws' clause. We do not have to handle them in place of occurrence because there is a handler for it. To discuss.

> 
>     * exceptions inheriting from the same class `EngineCodeException` are unnecessarily checked as they are caught in the same handler anyway - `@ExceptionHandler(EngineCodeException.class)` (regardless of whether all methods have `throws …` clause or not)

In my opinion it does not matter that we have checked or not checked exceptions and we catch them in handler. In my opinion effect is the same as previous - previous solution: catch each type of exception and do the same action, now: catch all in one method and do some action. If we need some other action for some specific exception, dedicated handle method will be created.

So, as before - the only gain of using checked exceptions in our case is that we have to use 'throws' clause. We do not have to handle them in place of occurrence because there is a handler for it. To discuss.

> 
>     * checked exceptions violate OCP

Why? In my opinion no in our case.

> 
>     * checked exceptions are useful when you expose the library to other API and want to force the user to handle the specific exception that your library throws, but we throw our custom exceptions in our app and we catch them in the same app

User cannot handle exceptions anyway. It does not matter if they are checked or not checked - they are being caught and information about it is being sent to user in ResponseEntity anyway and user shall do some action with that. When we use checked exceptions we (developers) get information that some method could cause some error and we shall do sth with it / it is handled in ExceptionHandler. In my opinion, we gained more control what is going on with methods. When we have RTE, we are not sure if there could be some error / if some corner case shall be considered. But maybe in other hand, when we have 'throws' it suggests to catch it... I think it is convention case, to discuss.

So, as before - the only gain of using checked exceptions in our case is that we have to use 'throws' clause. We do not have to handle them in place of occurrence because there is a handler for it. To discuss.

> 
>     * one of well known good practices is to **throw early, catch late** which makes us inform each intermediate method (when using checked excpts) that the exception can be thrown, which is less convenient and less readable than simply let the exception propagate to where it is caught/handled

For me it is more readable when I got information that some method throws ECExeption :)

> 
>     * small change regarding exception at a low level can cause large refactoring of the intermediate methods that propagate the exception to higher levels, but when using runtime exception no refactoring is needed

Why? It does not matter if it is checked or not checked exception in our case. We use parent class in 'throws' clause so changes in child exception does not affect the intermediate methods. 

> 
> So the checked exceptions are necessary sometimes, but it cannot be rule of thumb that we remove all runtime excpts and replace them with the checked ones.

In my opinion no. They are different opinions about that. To discuss.

> 
> Therefore we should stay with the runtime exceptions that were there from the beginning and just simplify the way they are used, we can talk about that.

pros of checked exceptions: 
+ throws is needed

cons of checked exceptions: 
- throws is needed

other:
- apps work in the same way

**Comment by michalrys** [comment]
conclusions:
- use RuntimeExceptions
- simplify EngineCodeErrors
- make exceptions more generic - to set up custom message and EngineCodeErrors enum

**Comment by michalrys** [comment]
Changes:
- our exceptions are unchecked - extending RuntimeException
- refactored for more generic uses
- SQLException catch in handler was removed - this exception is never being thrown
- RunTimeException in factory method in Entry was replaced by custom exception: NotSupportedEntryException. Some unit test was written for this one
- simplest implementation of Logger was done in order to prepare logging message

**Review by tom-zoladz — APPROVED** [review]

**Pull request merged**
